import { getLoginUserInfo } from "@/action/set-cookie";
import Navbar from "@/components/navbar/Navbar";
import { AuthProvider } from "@/provider/AuthProvider";
import { NotificationProvider } from "@/provider/NotificationProvider";
import { SocketProvider } from "@/provider/SocketProvider";
import type { Metadata } from "next";
import { Wix_Madefor_Text } from "next/font/google";
import { Toaster } from "sonner";
import "swiper/css";
import "swiper/css/effect-fade";
import "swiper/css/navigation";
import "swiper/css/pagination";
import "./globals.css";



const wixMadeforText = Wix_Madefor_Text({
  variable: "--font-wix-madefor-text",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const initialUser = await getLoginUserInfo();
  console.log(initialUser, "initialUser from layout");

  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          type="text/css"
          charSet="UTF-8"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.css"
        />
        <link
          rel="stylesheet"
          type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick-theme.min.css"
        />
      </head>
      <body
        className={`${wixMadeforText.variable} antialiased`}
        suppressHydrationWarning={true}
      >
        <AuthProvider initialUser={initialUser}>
          <SocketProvider>
            <NotificationProvider>
              <Toaster />
              <Navbar />
              {children}
            </NotificationProvider>
          </SocketProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
